### ISSUE TITLE
dude heard the sound of a revival source dropping

### ISSUE THREAD

**Issue by XyDark** [kineryy/tadah-eleven#2]
rushed to his PC like the flash to fork it

**Comment by XyDark** [comment]
THIS WAS THE WRONG PERSON

**Comment by XyDark** [comment]
Ahhh

**Comment by CUKESIM** [comment]
your just mad because i banned you from hromi

**Comment by kineryy** [comment]
you're*

**Comment by CUKESIM** [comment]
stfu furry

**Comment by kineryy** [comment]
Shut the fuck up, furry.*

**Comment by RYELOWAlly** [comment]
My guy is a fat fucking traggot nobody liesk and should hang himself with a 100yd noose you chapstick needing indian shit looking boy end it now

**Comment by RYELOWAlly** [comment]
DOnt ban me @ github rturst and saefty

**Comment by CUKESIM** [comment]
shut up this code is bad

**Comment by CUKESIM** [comment]
hromi source is so much better with php

**Comment by kineryy** [comment]
Shut up, this code is bad.*

**Comment by RYELOWAlly** [comment]
Bro you lips would be much better with chapstick

**Comment by gladosb5** [comment]
e

**Comment by CUKESIM** [comment]
my lips aren't even dry

**Comment by RYELOWAlly** [comment]
Yeah but yo grandma is boy nobody love u they all either ran away from ur dump ass or they died cause noone love ur dump ass u need a life and a job

**Comment by ghost** [comment]
# "kineryy created repository tadah-eleven"
[![image](https://cdn.calones.xyz/OYxC16N3TBg)]

**Comment by RYELOWAlly** [comment]
U say u dating someone on the internet bro u dating urself imagine being such a fucking loser u date urself thats next level

**Comment by CUKESIM** [comment]
what are you even saying

**Comment by RYELOWAlly** [comment]
Everyone keeps u around because they'd feel bad some loser 9 year old killed himself thats really what its about

**Comment by CUKESIM** [comment]
is this carrot (muhammed)

**Comment by RYELOWAlly** [comment]
Or u make shitty revivals all the time and all them 8 year olds eat them up its like a hierarchy

**Comment by CUKESIM** [comment]
what is a hierarchy

**Comment by RYELOWAlly** [comment]
My guy has grade 3 level intelligence

**Comment by kineryy** [comment]
PLEASE ARGUE OVER DISCORD THIS IS AMUSING ME BUT IDK IF GITHUB WILL LIKE THIS

**Comment by CUKESIM** [comment]
all i know is you're mamas pussy
