### ISSUE TITLE
...

### ISSUE THREAD

**Issue by CUKESIM** [kineryy/tadah-eleven#3]
why did you lock it kinery

**Comment by nopliers** [comment]
Get the fuck out u retarded mong

**Comment by nopliers** [comment]
Noone cares what u have to say leave now

**Comment by CUKESIM** [comment]
shut up mohamed

**Comment by I-Have-An-Issue** [comment]
USE SOME LIP BALM CRUSTY ASS

**Comment by CUKESIM** [comment]
YOUR LIPS ARE MORE DRY THEN MINE

**Comment by I-Have-An-Issue** [comment]
PROOOOOOOOOOOOOOOOOOOOOOOOOOOOOVE IT

**Comment by nopliers** [comment]
> shut up mohamed

Stfu bro shut up shaqqir or whatever ur dungass parents called ur black ass

**Comment by nopliers** [comment]
U look like fucking mud

**Comment by CUKESIM** [comment]
my parents arent dungass

yours are because your muslim

**Comment by prtzls** [comment]
Nigga face rougher then the sahara desert find the nearest lotion bottle you crocodile ass bitch

**Comment by nopliers** [comment]
Bro your parents look like dung to make someone as shitcovered like u

**Comment by CUKESIM** [comment]
bro you dont even use lotion on the lips you use lip balm your fucking retarded

**Comment by nopliers** [comment]
??? MY GUY DOESNT KNOW WHAT LIP BALM IS

**Comment by prtzls** [comment]
I said face you illiterate fuck

**Comment by CUKESIM** [comment]
you said lip

**Comment by nopliers** [comment]
??? YOUY SID YOU RAPED A DOG

**Comment by CUKESIM** [comment]
also i do know what lip balm is i just said it

**Comment by CUKESIM** [comment]
I DIDNT RAPE NO DOG

**Comment by prtzls** [comment]
"Nigga face rougher then the sahara desert find the nearest lotion bottle" Can you read or is the 3rd grade level english getting to u

**Comment by nopliers** [comment]
CAN YOU LEAVE THE ORC LIKE ACTUALLY NOONE WANTS YOUR RETARDED ASS HERE

**Comment by CUKESIM** [comment]
i already left the orc idiot

**Comment by nopliers** [comment]
MY GUY SAYS ILL LEAVE THE ORC NIGGA YOU STILL IN THE ORC!

**Comment by prtzls** [comment]
OBVIOUSLY NOT

**Comment by CUKESIM** [comment]
i blocked all the old roblox websites with my website blocker

**Comment by nopliers** [comment]
Well if u left it u wouldnt be making no retarded forks and caring about what xy said on the issue tracker

**Comment by CUKESIM** [comment]
its a premium extension i bought from the chrome web store

**Comment by nopliers** [comment]
Idc bro u clearly stalkingt he fucking tadah disc to be registering github accs purely to fork this

**Comment by nopliers** [comment]
U are genuinely braindead

**Comment by CUKESIM** [comment]
im not fucking braindead your the braindead one you fucking idiot

**Comment by nopliers** [comment]
![image](https://user-images.githubusercontent.com/100178530/156482428-55759a6d-4718-46e6-a181-4e4bfd9aa434.png)

**Comment by CUKESIM** [comment]
also the hosts doesnt work when i use a browser vpn so i needed a extension

**Comment by prtzls** [comment]
Hes braindead yet you cant find chapstick

**Comment by CUKESIM** [comment]
i did try to use the hosts file im not dumb it just doesnt work with vpn

**Comment by prtzls** [comment]
YOU ARE ACTUALLY

**Comment by CUKESIM** [comment]
also i dont even need chapstick my lips are fine

**Comment by nopliers** [comment]
Or u can practice self control and not fucking go on those sites but u seem to have a critical addiction to that shit to require you fucking BUY a chrome extension

**Comment by CUKESIM** [comment]
it was only 2 dollars

**Comment by nopliers** [comment]
It was only 2 dollars meanwhile i get that shit for free

**Comment by CUKESIM** [comment]
your mama down syndrome

**Comment by prtzls** [comment]
That was a banger

**Comment by nopliers** [comment]
U the embodiment of down syndrome nigga you patient 0 we need to kill yo ass to cure everyone else

**Comment by prtzls** [comment]
You need to die

**Comment by CUKESIM** [comment]
ALSO i ltierally tried the free one. AND IT DIDNT WORK.

**Comment by nopliers** [comment]
Seems like a you issue retard

**Comment by CUKESIM** [comment]
literaly*

**Comment by CUKESIM** [comment]
SHUT THE HELL UP CARROT

**Comment by prtzls** [comment]
This deadass like arguing with a zombie

**Comment by CUKESIM** [comment]
what do you mean im a gifted student

**Comment by nopliers** [comment]
""""""""""""""gifted""""""""""""""

**Comment by prtzls** [comment]
"Gifted student" in daycare

**Comment by CUKESIM** [comment]
"gifted"* you dont use more then one quote

**Comment by nopliers** [comment]
0 context clues u are the embodiment of low functioning autism

**Comment by woomyyylol** [comment]
hey do you guys like dinosaurs

**Comment by prtzls** [comment]
WHY ARE YOU TRYING TO CORRECT HIM YOU FUMBLED AT THE WORD "LITERALLY"

**Comment by prtzls** [comment]
> hey do you guys like dinosaurs

No

**Comment by CUKESIM** [comment]
what do you mean context clues nigga what are you dropping clues to

**Comment by nopliers** [comment]
Im dropping clues that they'd be showing on blues clues nigga you are not gifted you're "special" in that ur fucking braindead

**Comment by nopliers** [comment]
They tell u ur gifted cause they cant say "sorry ma'am ur kids a fucking retard"

**Comment by CUKESIM** [comment]
i got in the higher level class

**Comment by CUKESIM** [comment]
bro im not braindead

**Comment by nopliers** [comment]
??? U got in the class where niggas stick lima beans up they noses stfu

**Comment by CUKESIM** [comment]
im actually really smart

**Comment by prtzls** [comment]
Higher level in autism you sit on the short bus lame ahh nigga

**Comment by nopliers** [comment]
Cargo cult programmer headass calling themselves smart u are retarded

**Comment by CUKESIM** [comment]
my mom drives me i dont use the bus

**Comment by CUKESIM** [comment]
so idk what you even mean

**Comment by iagoMAO** [comment]
what the fuck

**Comment by nopliers** [comment]
The best thing yo ass know how to do is CTRL+C plus CTRL+V naw nigga you right click

**Comment by CUKESIM** [comment]
hey iago i remember you from a while ago

**Comment by CUKESIM** [comment]
are you trying to say i steal code

**Comment by EpicuIy** [comment]
stfu cukesim nobody likes you

**Comment by prtzls** [comment]
Ur nose grew while you said that statement

**Comment by CUKESIM** [comment]
EWWW EPICULY

go groom some 9 year olds

**Comment by EpicuIy** [comment]
fuk u

**Comment by nopliers** [comment]
Nigga you should groom your hair

**Comment by cukesimfan** [comment]
cukesim baby pls stop arguing

**Comment by nopliers** [comment]
???????????????????????

**Comment by prtzls** [comment]
LOL

**Comment by CUKESIM** [comment]
stfu epiculy u russian ass nigga 

your nigga gonna get drafted to ukranie and die

**Comment by prtzls** [comment]
BRO WHO

**Comment by cukesimfan** [comment]
stop n word pls cukesim baby

i love u i dont wnana see u swear

**Comment by nopliers** [comment]
Damn nigga what the fuck

**Comment by EpicuIy** [comment]
stop lying cukesim has no fans

**Comment by prtzls** [comment]
This convo got real weird reaal fast it was fun yall

**Comment by EpicuIy** [comment]
time to go work on rhodum again!

**Comment by lightbulblighter** [comment]
If you are looking for an image, it was probably deleted.

**Comment by cukesimfan** [comment]
also fuck u calone >:(

**Comment by nopliers** [comment]
Why areY OU HERE

**Comment by I-Have-An-Issue** [comment]
@CUKESIM June 19, 2022
![](https://cdn.discordapp.com/attachments/860639095310778413/948764478001000448/HalleLuty2-02.jpg)

**Comment by prtzls** [comment]
If cukesim can fix eleven.tadah i will be donating 100,000 boxes of chapstick to children in need thats all

**Comment by nopliers** [comment]
Carrot i was finna dm u but i remembered u were doing the bit

**Comment by CUKESIM** [comment]
@lightbulblighter hey muhamed

**Comment by brenden7158** [comment]
wtf

**Comment by nopliers** [comment]
??????????

**Comment by nopliers** [comment]
HEY "GIFTED" NIGGA KILL YOURSELF

**Comment by CUKESIM** [comment]
literally stfu

**Comment by cukesimfan** [comment]
cukesim wanna smash tonight??????
im so sorry we couldnt do it last night

**Comment by nopliers** [comment]
??????

**Comment by CUKESIM** [comment]
@cukesimfan are you parallelogram

**Comment by cukesimfan** [comment]
play with a nigga balls so you know im balling 😎

**Comment by CUKESIM** [comment]
actually dont even answer i know its you

**Comment by cukesimfan** [comment]
who is parallelogram

**Comment by cukesimfan** [comment]
im cukesimfan

**Comment by cukesimfan** [comment]
how about you hop in dm vc and we can erp and shit yknow

**Comment by CUKESIM** [comment]
stop playing dumb you fuckin nigga face

**Comment by I-Have-An-Issue** [comment]
Its like da rectangles n shit@cukesimfan

**Comment by cukesimfan** [comment]
do some of that hot esex

**Comment by EpicuIy** [comment]
stfu cukesim I ratted u with rhodum XD XD

**Comment by CUKESIM** [comment]
i dont even do esex

**Comment by brenden7158** [comment]
yall need help

**Comment by cukesimfan** [comment]
THATS SO MEAN

**Comment by cukesimfan** [comment]
CUKESIM I LOVE U BB

**Comment by nopliers** [comment]
NIgga im gay
![1622937626927](https://user-images.githubusercontent.com/100178530/156483614-1eb08c12-cc7a-4dfd-afaf-c602ee900cc7.jpg)
im mad horny wdyall think abt this

**Comment by CUKESIM** [comment]
oh thats soo hot

**Comment by cukesimfan** [comment]
SAME 
FOR CUKESIM

**Comment by cukesimfan** [comment]
omg cukesim u also think its hot bb??? we should fuck

**Comment by lightbulblighter** [comment]
> Why areY OU HERE

![28132487-3658-417F-B125-E61E64D7D673](https://user-images.githubusercontent.com/59720715/156483691-b94ae6a3-2810-4ae4-a1b1-9e0cdc626157.jpeg)

**Comment by kineryy** [comment]
Please stop for the love of God

**Comment by cukesimfan** [comment]
fr let me unzip your pants and sug on that juicy 10 inch bbc

**Comment by nopliers** [comment]
Yoo. Finally the issue resolved

**Comment by CUKESIM** [comment]
should i stop this guys?
