### ISSUE TITLE
stop locking

### ISSUE THREAD

**Issue by CUKESIM** [kineryy/tadah-eleven#5]

**Comment by cukesimfan** [comment]
FR

**Comment by cukesimfan** [comment]
IMMEDIATELY

**Comment by cukesimfan** [comment]
CUKESIM LETS SMASH

**Comment by CUKESIM** [comment]
stfu bro

**Comment by cukesimfan** [comment]
I REALLY WANT THAT 10 INCH BBC IN MY MOUTH SLOPPY TOPPY AND SHIT YKNOW

**Comment by cukesimfan** [comment]
NAH NAH NAH YOU LIKE IT WHEN MY MOUTH OPEN THO, RIGHT?

**Comment by CUKESIM** [comment]
how do i lock someone on github

**Comment by CUKESIM** [comment]
block*

**Comment by brenden7158** [comment]
yall ain't funny

**Comment by cukesimfan** [comment]
GOING GAWK GAWK GAWK ON YOUR COCK

**Comment by cukesimfan** [comment]
SLOPPERY SLIPPERY ON UR COCK

**Comment by CUKESIM** [comment]
im not even trying to be funny im just talking

**Comment by cukesimfan** [comment]
ok?

**Comment by asdaeshndj** [comment]
fuck off

**Comment by cukesimfan** [comment]
add me on discord bb

**Comment by cukesimfan** [comment]
how about you fuck off

**Comment by cukesimfan** [comment]
i fucking love cukesim

**Comment by gabe-12** [comment]
i like women

**Comment by nopliers** [comment]
Bruh im mad horny who wanna erp
